config/routes.rb
Srdr::Application.routes.draw do

  get "search_registry" => "registry_usage#search_registry"

    root :to => 'home#index'

    resources :ef_instructions

    resources :comments

    resources :extraction_forms, :study_extraction_forms, :extraction_form_arms, :extraction_form_diagnostic_tests, :extraction_form_adverse_events
    resources :extraction_form_sections, :study_extraction_form_sections
    resources :users, :password_resets,  :user_project_roles, :user_sessions
    resources :quality_rating_fields, :quality_rating_data_points
    resources :adverse_events, :adverse_event_results, :adverse_event_columns
    resources :design_details, :design_detail_fields, :design_detail_data_points
    resources :primary_publications, :primary_publication_numbers, :secondary_publications, :secondary_publication_numbers
    resources :outcome_comparison_results, :outcome_comparison_columns
    resources :quality_dimension_fields, :quality_dimension_data_points
    resources :baseline_characteristics, :baseline_characteristic_fields, :baseline_characteristic_data_points
    resources :arm_details, :arm_detail_fields, :arm_detail_data_points
    resources :outcome_details, :outcome_detail_fields, :outcome_detail_data_points
    resources :quality_details, :quality_detail_fields, :quality_detail_data_points
    resources :diagnostic_test_details, :diagnostic_test_detail_fields, :diagnostic_test_detail_data_points
    resources :arms, :diagnostic_tests
    resources :outcomes, :outcome_columns, :outcome_results, :outcome_timepoints, :extraction_form_outcome_names
    resources :key_questions, :studies_key_questions
    resources :outcome_measures, :outcome_data_points
    resources :comparisons

    resources :studies do
        resources :arms
        get 'data'
        get 'edit_split' => 'studies#edit_split'
    end

    resources :feedback_items

    get "home/index"
    get "user_sessions/new"
    get "primary_publications/get_pubmed_data"
    # ---------- not sure if needed [MK] ---------------
    #get "adv_search/index"

    resource :account, :controller                     => "users"
    get "account/email_preferences"                    => "users#email_preferences"
    post "account/toggle_email_preference/:project_id" => "users#toggle_email_preference"
    post "account/turn_on_all_email_reminders"         => "users#turn_on_all_email_reminders"
    post "account/turn_off_all_email_reminders"        => "users#turn_off_all_email_reminders"

    # ---------- New Audit trail support ---------------
    get "audit_trails/new"

    # ---------- DAA Info page ------------
    get  "daa/info"                => "daa_info#info"
    get  "daa/eligibility"         => "daa_info#eligibility"
    get  "daa/not_eligible"        => "daa_info#not_eligible"
    post "daa/eligible"            => "daa_info#eligible"
    post "daa/create_participant"  => "daa_info#create"

    # --------- DAA Consent form ----------
    get  "daa/consent"      => "daa_info#consent"
    get  "daa/thanks"       => "daa_info#consent_thanks"
    get  "daa/consent_form" => "daa_info#consent_form"
    post "daa/consent"      => "daa_info#consent_submit"

    # ---------- EPC Questionnaire ----------
    get "questionnaire/form" => "bryant_form#form"
    post "questionnaire/save" => "bryant_form#save"

    # hiding the ahrq header
    match '/application/go_full_screen' => 'application#toggle_ahrq_header'

    # used for adding and removing extraction forms to and from studies
    match 'projects/api_index_published' => 'projects#api_index_published'
    match 'projects/published' => 'projects#published'
    match 'home/quarterly_training'
    match 'home/external_resources'
    match 'register' => 'users#new'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'register/confirmation' => 'users#confirmation'
    match 'register/reviewconfirmation' => 'users#reviewconfirmation'
    match 'register/error' => 'users#error'
    match 'register/agreement_error' => 'users#agreement_error'
    match 'account/validation.html' => 'users#validateuser'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'projects/:project_id/studies/extraction_form_add' => 'studies#extraction_form_add'
    match 'projects/:project_id/studies/extraction_form_remove' => 'studies#extraction_form_remove'
    match 'projects/:project_id/studies/:id/extraction_form_add' => 'studies#extraction_form_add_edit'
    match 'projects/:project_id/studies/:id/extraction_form_remove' => 'studies#extraction_form_remove_edit'
    match 'projects/:id/extraction_forms' => 'projects#extractionforms'
    match 'projects/:project_id/extraction_forms/new' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/arms' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/:id' => 'extraction_forms#show'
    match 'projects/:project_id/extraction_forms/:extraction_form_id/import' => 'extraction_form_section_copies#import_from_previous_forms'
    match 'extraction_form_section_copies/save_import_request'

    match 'projects/:id/studies' => 'projects#studies'
    match 'projects/:id/users' => 'projects#users'
    match 'projects/:id/review' => 'projects#review'
    match 'projects/:id/publish' => 'projects#publish'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120204 - added support for table creator
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/tablecreator' => 'tablecreator#index'
    match 'tablecreator/buildtable' => 'tablecreator#buildtable'
    match 'tablecreator/templatemanager' => 'tablecreator#templatemanager'
    match 'projects/tablecreator/templatemanager' => 'tablecreator#templatemanager'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20121004 - added support for export tools
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/exporttools' => 'exporttools#index'
    match 'projects/exporttools/simpleexport' => 'exporttools#simpleexport'
    match 'projects/exporttools/advexport' => 'exporttools#advexport'
    match 'projects/exporttools/reportbuilder' => 'exporttools#reportbuilder'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120316 - added support for comparing studies - aka double extraction
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/:id/create_consensus' => 'studyconsensus#createconsensus'
    match 'comparestudies/create_consensus' => 'studyconsensus#createconsensus'
    match '/compexporter/saveas_excel/:project_id'=>'studyconsensus#export_to_excel'

    # used for adding extraction forms to project key questions
    #match 'extraction_forms/assign_key_questions' => 'extraction_forms#assign_key_questions'
    resources :projects do
        resources :studies do
            resources :arms, :secondary_publications, :primary_publications
            resources :extraction_forms do
                resources :outcome_measures do
                    post :edit, :save, :cancel
                    delete :destroy
                end
                resources :outcome_timepoints do
                    post :edit, :save, :cancel
                    delete :destroy_modal
                    delete :destroy
                end
            end
        end
        resources :extraction_forms
        resources :key_questions
    end

    match 'forgot_password' => 'password_resets#new'

    match 'projects/cancel_new' => 'projects#cancel_new'
    # match 'projects/:id/studies' => 'studies#index'

    match 'projects/:project_id/extraction_forms/:extraction_form_id/preview' => 'extraction_forms#preview'

    # copy a project
    match 'projects/show_copy_form'
    match 'projects/show_copy_request_form'
    match 'projects/request_a_copy'
    match 'projects/copy'
    match 'projects/:project_id/remove_parent_association' => 'projects#remove_parent_association'

    # key questions routes
    match 'key_questions/new' => 'key_questions#new'
    match 'key_questions/show' => 'key_questions#show'
    match 'key_questions/hide' => 'key_questions#hide'
    match 'projects/new/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/new' => 'key_questions#new'
    match 'projects/:project_id/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/:key_question_id/edit' => 'key_questions#edit'

    # getting comment content for all pages
    match 'projects/get_comment_content' => 'comments#show'
    match 'projects/:project_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_content' => 'comments#show'

    match 'projects/get_comment_summary' => 'comments#show_summary'
    match 'get_comment_summary' => 'comments#show_summary'

    # getting comment form from all pages
    match 'projects/get_comment_form' => 'comments#new'
    match 'projects/:project_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_form' => 'comments#new'

    # getting flag form from all pages
    match 'projects/get_flag_form' => 'comments#new_flag'

app/views/outcome_data_entries/_choose_timepoint.html.erb
<% unless @checkbox_timepoints.length == @selected_tp_array.length %>
<br/><label for="Add inactive timepoints using this form">You are not using the following timepoints, but may add them again if you wish: </label>
<br/>
<%= form_tag "results/update_table_rows", :remote=>true do %>
	<input type="hidden" name="outcome_id" value="<%= @outcome.id %>"/>
	<input type="hidden" name="subgroup_id" value="<%= @subgroup.nil? ? 0 : @subgroup.id %>">
	<input type="hidden" name="selected_timepoints" value="<%= @selected_timepoints %>"/>
	<input type='hidden' name='project_id' value="<%= @project_id %>"/>
<table width="300px">
	<tr>
		<td width="50%">
			<% @checkbox_timepoints.each do |tp| %>
			  <% if !@selected_tp_array.include?(tp.id.to_s)%>  
			  	<input id="<%= "checkbox_#{tp.id}" %>" type='checkbox' name='tps_to_add[]' value="<%= tp.id %>" />
			  	<%= tp.number %> <%= tp.time_unit %><br/>
			  <% end %>
			<% end %>
		</td>
		<td width="50%"><button type='submit' id="button_to_submit_row_update">Update Table Rows</button></td>
  </tr>
</table>

<% end %>
<% end %>
<script type='text/javascript'>
<!--
if($("#button_to_submit_row_update").length > 0){
	$("#button_to_submit_row_update").bind("click",function(){
		$(this).after("<img id='waitingGIF' src='/images/waiting.gif' alt='waiting...'/>");
	});
}
//-->
</script>

app/views/outcome_data_entries/_data_point_options_form.html.erb
<% form_tag "results/assign_data_point_attributes", :remote=>true do%>
<div style="padding:10px;">
	<input type='hidden' name='datapoint_id' value="<%= @datapoint.id %>">
	<input type='hidden' name='datapoint_type' value="<%= @dp_type %>">
	<input type='hidden' name='outcome_id' value="<%= @outcome_id %>">
	<input type='hidden' name='subgroup_id' value="<%= @subgroup_id %>">
	<input type='hidden' name='selected_timepoints' value="<%= @selected_timepoints %>">
	<input type='hidden' name='field_id' value="<%= @field_id %>">
	<strong>The data in this cell is: </strong><br/>
	<input title="Choose that this is not a calculated field." type="radio" name="is_calculated" value="0" <%= @datapoint.is_calculated ? "" : "checked" %>> 	  not calculated (straight from the article)<br>
	<input type="radio" title="Choose that this is a calculated field." name="is_calculated" value="1" <%= @datapoint.is_calculated ? "checked" : "" %>> 
    calculated  
  <br/><br/>
	<strong>Footnote Text:</strong></br>
	<textarea rows=4 cols=50 id="footnote_text_area" name="footnote"><%=@datapoint.footnote%></textarea>
  <br/>
	Characters remaining: 
	<span id='chars_remaining'>
		<% if @datapoint.footnote.nil? %>
		  255
		<% else %>
		  <%= 255 - @datapoint.footnote.length %>
		<% end %>
	</span>
	
</div>
<br/>
	<center>
		<button type="submit" class="positive" data-disable-with='<%= ajax_wait_msg %>'>
			<%= image_tag "Add.png", :alt => "Add" %> Save
		</button>
		<button class="negative" onClick="event.preventDefault();$('#data_point_option_div').dialog('close');">
			<%= image_tag "Cancel.png", :style=>"vertical-align:text-top;", :alt => "Cancel" %> Cancel
		</button>
	</center>
<% end %>
<script type='text/javascript'>
<!--
$("#footnote_text_area").bind('keyup change',function(){
	var max = 255;
	var current = $(this).val().toString().length
	remaining = max - current;
	if(remaining < 0){
		var thisval = $(this).val()
		thisval = thisval.substring(0,max);
		$(this).val(thisval);
		remaining = 0;
	}
	$("#chars_remaining").html(remaining)
})

-->
</script>

app/views/outcome_data_entries/_footnotes.html.erb
<% unless @footnotes.empty? %>
	<table style='width:100%;' class='list_table'>
	<tr><th colspan='2' style='text-align:left;'>Footnotes</th></tr>
	<% @footnotes.each_with_index do |fn,index| %>
	  <tr>
	  	<td valign='top' align='center' width='25px'>
	  		<% unless @footnotes.length < 2 %>
	  			<select class="footnote_sort_selector" title="Adjust the order of footnotes" orig_value="<%= index + 1 %>" style="height:20px;width:40px;font-size:11px;">  
	  			  <% for i in 1..@footnotes.length %>
	  			    <% sel = (i == index+1) ? "selected" : "" %>
	  			    <option value="<%= i %>" <%= sel %>><%= i %></option>
	  			  <% end %>
	  			</select>	
				<% else %>
				  <strong><%= fn.footnote_number %>.</strong></td>
				<% end %>
			</td>	
	    <td valign='top'><%= fn.footnote %></td>
	  </tr>
	<% end %>
	</table>
<% end %>
<script type='text/javascript'>
// <!--
/* When users update the footnote order, update all footnote numbers
   and update the entry table accordingly.
*/
if( $(".footnote_sort_selector").length > 0){
	$(".footnote_sort_selector").unbind();
	$(".footnote_sort_selector").bind("change",function(){
		origVal = $(this).attr("orig_value");
		newVal = $(this).val();
		$.ajax({
			type: 'POST',
			url: 'results/update_footnote_order',
			data:({
				original_value: origVal,
				new_value: newVal,
				outcome_id: "<%= @outcome_id %>",
				subgroup_id: "<%= @subgroup.nil? ? 0 : @subgroup.id %>",
				selected_timepoints: "<%= @selected_timepoints %>"
			}),
			success: function(){
				$("#loading_div").remove();
			}
		})
		show_loading_icon();
	})
}

// -->
</script>

app/views/outcome_data_entries/_measures_form.html.erb
<% selected_titles = @selected_measures.collect{|x| x.title}%>
<% all_titles = @all_measures.collect{|x| x.title} %>
<% userdef_titles = @all_user_defined_measures.collect{|x| x.title} %>
<% stragglers = selected_titles - all_titles - userdef_titles %>
<% previously_checked = ""%>
<% previously_defined_checked = "" %>
<% submit_path = @show_measures_for=="Outcome" ? "results/update_measures" : "results/update_comparison_measures" %>
<% form_tag submit_path, :remote=>true do %>
<!--
 Cycle through all possible measures defined in the default measures table for this outcome
 type. If the measure is also defined in the study, then check the box. Otherwise, leave it unchecked	
-->
<!--<div style='width:100%; height:97%; overflow:auto;' id='measure_container'> -->
<div id='measure_form_container'>	
  <table class='measures_table'>
		<tr>
			<th colspan='2'>
  			I would like to edit measures for:
  		</th>
  	</tr>
    <tr>
	  	<td colspan='2'>
	  		<% individual = "This timepoint only"%>
	  		<% group = "All timepoints in this outcome" %>
	  		<% if @show_measures_for == 'Within-Arm Comparison' %>
	  		  <% individual = "This comparison only"%>
	  		  <% group = "All comparisons in the within-arm comparison table" %>
	  		<% elsif @show_measures_for == 'Between-Arm Comparison' %>
	  		  <% individual = "This timepoint only" %>
	  		  <% group = "All timepoints in the between-arm comparison table" %>
	  		<% end %>
				<input type="radio" name="changes_apply_to" id="apply_changes_to" value="this" checked/> <%= individual %><br />
				<input type="radio" name="changes_apply_to" id="apply_changes_to" value="all"/> <%= group %>
			</td>
		</tr>
  	
    <% previous_group = 0%>
  	<%# The measure type descriptions for each section %>
  	<% titles = {1=>"Descriptive Statistics",2=>"Descriptive Statistics",3=>"Statistical Tests",4=>"Methods of Estimation",5=>"Adjusted Statistical Tests",6=>"Adjusted Methods of Estimation"}%>
  	<% @all_measures.each do |meas| %>
	  <% if meas.measure_type != previous_group %>
	    <% if previous_group.even? %>
	    		<tr>
	        	<th colspan=2><%= titles[previous_group + 1]%></th>
	        </tr>
	      <% if previous_group == 0 %>
	        <tr><td valign='top' >
	      <% else %>
      		</td></tr><tr><td valign='top'>
      	<% end %>
	    <% else %>
    		</td><td valign='top'>
    	<% end %>
    	<% previous_group += 1 %>
	  <% end %>
	  <br/>
		<% checked = selected_titles.include?(meas.title) ? "checked" : ""%>
		<% selected_meas_id = 0 %>
		<% if checked == "checked" %>
		  <% selected_meas_id = @selected_measures[selected_titles.index(meas.title)].id %>
		  <% previously_checked += previously_checked == "" ? "#{selected_meas_id}" : "_#{selected_meas_id}" %>
	  <% end %>
	  <% hashkey = "#{meas.id}_#{selected_meas_id}"%>
		<input type="checkbox" name="<%= "measures[#{hashkey}]"%>" id="<%= "measure_#{hashkey}"%>" <%= checked %>/> <%= checked=="checked" ? render(:inline=>"<span class='selected_measure m_title'> #{meas.title} </span>") : render(:inline=>"<span class='m_title'>#{meas.title}</span>") %>
	<% end %> <%# end all_measures.each %>
  </td>
	</tr>
  <% unless @all_user_defined_measures.empty? && stragglers.empty? %>
		<tr>
	  	<th colspan='2'>
	  	  User-Defined Measures
	  	</th>
	  </tr>
	  <tr>
	  	<th width="35%">
	  		Title
	  	</th>
	  	<th>
	  		Description
	  	</th>
	  </tr>
	  <%# selected_titles = @selected_measures.collect{|x| x.title} %>
	  <% previous_defined_checked = "" %>
	  <% @all_user_defined_measures.each do |measure| %>
	    <tr class='defined_measure_row'>
	    <td>
	    <% checked = selected_titles.include?(measure.title) ? "checked" : "" %>
	    <% selected_meas_id = 0 %>
	    <% if checked == "checked" %>
	      <% selected_meas_id = @selected_measures[selected_titles.index(measure.title)].id %>
		  <% previously_defined_checked += previously_defined_checked == "" ? "#{selected_meas_id}" : "_#{selected_meas_id}" %>
	    <% end %>
	    <% hashkey = "#{measure.id}_#{selected_meas_id}"%>
			<input type="checkbox" name="<%= "user_defined_measures[#{hashkey}]"%>" id="<%= "user_defined_measure_#{hashkey}"%>" <%= checked %>/> <%= checked=="checked" ? render(:inline=>"<span class='selected_measure m_title'> #{measure.title} </span>") : render(:inline=>"<span class='m_title'>#{measure.title}</span>") %>
			</td>
			<td><%= measure.description %></td>
			</tr>
	  <% end %>
    <%# stragglers %>
    <% stragglers.each do |straggler| %>
      <% selected_measure = @selected_measures[selected_titles.index(straggler)] %>
      <% previously_defined_checked += previously_defined_checked == "" ? "#{selected_measure.id}" : "_#{selected_measure.id}" %>
      <tr class='defined_measure_row'>
      <td>
      <% checked = "checked" %>
      <% selected_meas_id = 0 %>
    
      <% hashkey = "#{selected_measure.id}_#{selected_measure.id}"%>
      <input type="checkbox" name="<%= "user_defined_measures[#{hashkey}]"%>" id="<%= "user_defined_measure_#{hashkey}"%>" <%= checked %>/> <%= checked=="checked" ? render(:inline=>"<span class='selected_measure m_title'> #{selected_measure.title} </span>") : render(:inline=>"<span class='m_title'>#{selected_measure.title}</span>") %>
      </td>
      <td><%= selected_measure.description %></td>
      </tr>
    <% end %>

    </tr>
	<% end %>
  <tr id="new_measure_title_row" class='new_measure_row'>
  	<th colspan='2'>
      <% unless (@project_id.to_i == 427 || @project_id.to_i == 553) %>
  		  <a href='#' id='define_measure_link'><img alt="Add a User-Defined measure" src='/images/add_user_defined_measure.png' title='Add a User-Defined Measure'/></a>
      <% end %>
  	</th>
  </tr>
  
</table> <%# complete the end of the table %>
	
  <input type="hidden" name="previously_checked" value="<%= previously_checked %>"/>
  <input type="hidden" name="previously_defined_checked" value="<%= previously_defined_checked %>"/>
	<input type="hidden" name="timepoint_id" value="<%= @timepoint_id %>">
  <input type="hidden" name="selected_timepoints" value="<%= @selected_timepoints %>"/>
  <%# used only by the outcome measures%>
  <input type="hidden" name="ocde_id" value="<%= @ocde_id %>">  
  <%# used only by the comparison measures%>
  <input type="hidden" name="comparison_id" value="<%= @comparison_id %>"/>
  <input type="hidden" name="subgroup_id" value="<%= @subgroup_id %>"/>
  <span id='bottom_anchor'></span>
</div> <%# end the overflow div %>
	<center>
		<button type="submit" id="save_measures_btn" class="positive" data-disable-with='<%= ajax_wait_msg %>'>
			<%= image_tag "Add.png", :alt => "Add" %> Save
		</button>
		<button class="negative" id="cancel_measures_form_btn">
			<%= image_tag "Cancel.png", :style=>"vertical-align:text-top;", :alt => "Cancel" %> Cancel
		</button>
  </center>
<% end %> <%# end the form%>

<% next_new_measure_id = -1 %>
<script type='text/javascript'>
<!--
function measures_init(){
  try{
    checkMeasuresFormLoaded(); // HOLD OFF UNTIL THE LAST ELEMENT IS LOADED
    prepareMeasuresForm();
  } catch( err ) {
    setTimeout('measures_init()', 200);
  }
}
function checkMeasuresFormLoaded(){
  if ( $('#cancel_measures_form_btn').length == 0){
    $jquery.error( 'not ready' );
  }
}

function prepareMeasuresForm(){

  $("#cancel_measures_form_btn").unbind("click");
  $("#cancel_measures_form_btn").bind("click",function(event){
    event.preventDefault();
    $('#modal_div').dialog('close');
  });

  /* WHEN THE CHECKBOXES ARE PRESSED, TOGGLE THE TITLE HIGHLIGHTING
     DEPENDING ON WHETHER OR NOT IT'S SELECTED */
  $(':checkbox').unbind("click");
  $(':checkbox').bind("click",function(){
    id_to_search = "#" + $(this).attr("id") + " + .m_title";
    span_element = $(id_to_search.toString());
    if($(span_element).hasClass("selected_measure")){
      $(span_element).removeClass("selected_measure");
    }else{
      $(span_element).addClass("selected_measure");
    }
  });
  var next_new_measure_id = -1;
  $("#define_measure_link").bind("click",function(event){
    event.preventDefault();
    
    /*$("#new_measure_title_row").show();*/
    $($(".new_measure_row").last()).after("<tr class='new_measure_row' id='new_measure_row_"+next_new_measure_id+"'><td><input type='checkbox' checked disabled><input type='text' size=30 class='tmp_input' name='user_defined_titles["+next_new_measure_id+"]' value='Enter a Title Here'></td><td><div style='float:right;'><a href='#' class='remove_measure_button' row_id='"+next_new_measure_id+"'>Remove</a></div><input type='text' size=50 class='tmp_input' name='user_defined_descriptions["+next_new_measure_id+"]' value='Enter a Description Here'></td></tr>")
    $("#measure_container").scrollTop(9999);
    next_new_measure_id = next_new_measure_id - 1;
  });

  $(".remove_measure_button").live("click",function(event){
    event.preventDefault();
    row = $(this).attr("row_id");
    rowid = "#new_measure_row_"+row.toString();
    $(rowid).remove();
  });

  $(".tmp_input").live("click",function(){
    $(this).val("");
    $(this).removeClass("tmp_input");
  });
}

measures_init(); // attach everything for the measures form
//-->
</script>

app/views/outcome_data_entries/_view_modify_link.html.erb
<% unless @existing_results.empty? && @existing_comparisons.empty? %>
	<br/>
	OR <a href='#' tabindex='230' id="view_modify_entry_link" title="View/Modify Existing Results Entries" class='toggle_existing_results_link'>View/Modify Existing Data Entries</a>	
	<br/>
<% else %>
  
<% end %>

app/views/outcome_data_entries/refresh_existing_results.js.erb
// UPDATE THE CORRESPONDING EXISTING RESULTS TABLE
<% unless @is_diagnostic %>
	<% unless @existing_results.empty? %>
		$("#existing_results_div").html("<%= escape_javascript(render :partial=>"/outcome_data_entries/existing_results")%>");
	<% else %>
		$("#view_modify_link_div").hide();
		$("#view_modify_link_div").html("");
		$("#existing_results_div").html("");
	<% end %>
<% else %>
	<% unless @existing_comparisons.empty? and @existing_comparators.empty? %>
		$("#existing_results_div").html("<%= escape_javascript(render :partial=>"/outcome_data_entries/existing_diagnostic_results")%>");
	<% else %>
		$("#view_modify_link_div").hide();
		$("#view_modify_link_div").html("");
		$("#existing_results_div").html("");
	<% end %>
<% end %>

app/views/outcome_data_entries/show_between_arm_comparison_table.js.erb
$("#entry_div").html("<%= escape_javascript(render :partial=>"comparisons/between_arm_continuous")%>");

app/views/outcome_data_entries/show_data_point_options_form.js.erb
<% if @datapoint.nil? %>
	$("#confirmation_modal").html("You must save a value for this field before any options can be set.")
	$("#confirmation_modal").dialog({
	 	resizable: false,
		height: 160,
		modal: true,
		buttons: {
			"Cancel": function(){
				$(this).dialog("close");
			}
		}
	})
<% else %>
  $("#data_point_option_div").html("<%= escape_javascript(render :partial=>"/outcome_data_entries/data_point_options_form")%>");
	$("#data_point_option_div").dialog("option","resizable",true);
	$("#data_point_option_div").dialog("open");
<% end %>

app/views/outcome_data_entries/show_entry_table.js.erb
<% unless @OCDEs.empty? %>
	$("#form_div").html("<%= escape_javascript(render :partial=>"/outcome_data_entries/entry_table")%>");
<% else %>
  $("#entry_div").html("");
<% end %>

app/views/outcome_data_entries/show_measures_form.js.erb
$("#modal_div").dialog("option","resizable",true);
$("#modal_div").html("<%= escape_javascript(render :partial=>'/outcome_data_entries/measures_form')%>");
$("#modal_div").dialog("open");

app/views/outcome_data_entries/update_footnote_order.js.erb
$("#footnotes_div").html("<%= escape_javascript(render :partial=>"outcome_data_entries/footnotes")%>");

var tags = $(".footnote_tag");
original_value = parseInt("<%= @original_value%>");
new_value = parseInt("<%= @new_value%>");

for(i=0; i < tags.length; i++){
	var current_val = parseInt($(tags[i]).html());
	if(current_val == original_value){
		$(tags[i]).html(new_value)
	}else if((current_val <= new_value) && (current_val > original_value)){
		current_val = current_val - 1;
		$(tags[i]).html(current_val);
	}else if((current_val >= new_value) && (current_val < original_value)){
		current_val = current_val + 1;
		$(tags[i]).html(current_val)
	}
}