config/routes.rb
Srdr::Application.routes.draw do

  get "search_registry" => "registry_usage#search_registry"

    root :to => 'home#index'

    resources :ef_instructions

    resources :comments

    resources :extraction_forms, :study_extraction_forms, :extraction_form_arms, :extraction_form_diagnostic_tests, :extraction_form_adverse_events
    resources :extraction_form_sections, :study_extraction_form_sections
    resources :users, :password_resets,  :user_project_roles, :user_sessions
    resources :quality_rating_fields, :quality_rating_data_points
    resources :adverse_events, :adverse_event_results, :adverse_event_columns
    resources :design_details, :design_detail_fields, :design_detail_data_points
    resources :primary_publications, :primary_publication_numbers, :secondary_publications, :secondary_publication_numbers
    resources :outcome_comparison_results, :outcome_comparison_columns
    resources :quality_dimension_fields, :quality_dimension_data_points
    resources :baseline_characteristics, :baseline_characteristic_fields, :baseline_characteristic_data_points
    resources :arm_details, :arm_detail_fields, :arm_detail_data_points
    resources :outcome_details, :outcome_detail_fields, :outcome_detail_data_points
    resources :quality_details, :quality_detail_fields, :quality_detail_data_points
    resources :diagnostic_test_details, :diagnostic_test_detail_fields, :diagnostic_test_detail_data_points
    resources :arms, :diagnostic_tests
    resources :outcomes, :outcome_columns, :outcome_results, :outcome_timepoints, :extraction_form_outcome_names
    resources :key_questions, :studies_key_questions
    resources :outcome_measures, :outcome_data_points
    resources :comparisons

    resources :studies do
        resources :arms
        get 'data'
        get 'edit_split' => 'studies#edit_split'
    end

    resources :feedback_items

    get "home/index"
    get "user_sessions/new"
    get "primary_publications/get_pubmed_data"
    # ---------- not sure if needed [MK] ---------------
    #get "adv_search/index"

    resource :account, :controller                     => "users"
    get "account/email_preferences"                    => "users#email_preferences"
    post "account/toggle_email_preference/:project_id" => "users#toggle_email_preference"
    post "account/turn_on_all_email_reminders"         => "users#turn_on_all_email_reminders"
    post "account/turn_off_all_email_reminders"        => "users#turn_off_all_email_reminders"

    # ---------- New Audit trail support ---------------
    get "audit_trails/new"

    # ---------- DAA Info page ------------
    get  "daa/info"                => "daa_info#info"
    get  "daa/eligibility"         => "daa_info#eligibility"
    get  "daa/not_eligible"        => "daa_info#not_eligible"
    post "daa/eligible"            => "daa_info#eligible"
    post "daa/create_participant"  => "daa_info#create"

    # --------- DAA Consent form ----------
    get  "daa/consent"      => "daa_info#consent"
    get  "daa/thanks"       => "daa_info#consent_thanks"
    get  "daa/consent_form" => "daa_info#consent_form"
    post "daa/consent"      => "daa_info#consent_submit"

    # ---------- EPC Questionnaire ----------
    get "questionnaire/form" => "bryant_form#form"
    post "questionnaire/save" => "bryant_form#save"

    # hiding the ahrq header
    match '/application/go_full_screen' => 'application#toggle_ahrq_header'

    # used for adding and removing extraction forms to and from studies
    match 'projects/api_index_published' => 'projects#api_index_published'
    match 'projects/published' => 'projects#published'
    match 'home/quarterly_training'
    match 'home/external_resources'
    match 'register' => 'users#new'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'register/confirmation' => 'users#confirmation'
    match 'register/reviewconfirmation' => 'users#reviewconfirmation'
    match 'register/error' => 'users#error'
    match 'register/agreement_error' => 'users#agreement_error'
    match 'account/validation.html' => 'users#validateuser'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'projects/:project_id/studies/extraction_form_add' => 'studies#extraction_form_add'
    match 'projects/:project_id/studies/extraction_form_remove' => 'studies#extraction_form_remove'
    match 'projects/:project_id/studies/:id/extraction_form_add' => 'studies#extraction_form_add_edit'
    match 'projects/:project_id/studies/:id/extraction_form_remove' => 'studies#extraction_form_remove_edit'
    match 'projects/:id/extraction_forms' => 'projects#extractionforms'
    match 'projects/:project_id/extraction_forms/new' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/arms' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/:id' => 'extraction_forms#show'
    match 'projects/:project_id/extraction_forms/:extraction_form_id/import' => 'extraction_form_section_copies#import_from_previous_forms'
    match 'extraction_form_section_copies/save_import_request'

    match 'projects/:id/studies' => 'projects#studies'
    match 'projects/:id/users' => 'projects#users'
    match 'projects/:id/review' => 'projects#review'
    match 'projects/:id/publish' => 'projects#publish'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120204 - added support for table creator
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/tablecreator' => 'tablecreator#index'
    match 'tablecreator/buildtable' => 'tablecreator#buildtable'
    match 'tablecreator/templatemanager' => 'tablecreator#templatemanager'
    match 'projects/tablecreator/templatemanager' => 'tablecreator#templatemanager'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20121004 - added support for export tools
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/exporttools' => 'exporttools#index'
    match 'projects/exporttools/simpleexport' => 'exporttools#simpleexport'
    match 'projects/exporttools/advexport' => 'exporttools#advexport'
    match 'projects/exporttools/reportbuilder' => 'exporttools#reportbuilder'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120316 - added support for comparing studies - aka double extraction
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/:id/create_consensus' => 'studyconsensus#createconsensus'
    match 'comparestudies/create_consensus' => 'studyconsensus#createconsensus'
    match '/compexporter/saveas_excel/:project_id'=>'studyconsensus#export_to_excel'

    # used for adding extraction forms to project key questions
    #match 'extraction_forms/assign_key_questions' => 'extraction_forms#assign_key_questions'
    resources :projects do
        resources :studies do
            resources :arms, :secondary_publications, :primary_publications
            resources :extraction_forms do
                resources :outcome_measures do
                    post :edit, :save, :cancel
                    delete :destroy
                end
                resources :outcome_timepoints do
                    post :edit, :save, :cancel
                    delete :destroy_modal
                    delete :destroy
                end
            end
        end
        resources :extraction_forms
        resources :key_questions
    end

    match 'forgot_password' => 'password_resets#new'

    match 'projects/cancel_new' => 'projects#cancel_new'
    # match 'projects/:id/studies' => 'studies#index'

    match 'projects/:project_id/extraction_forms/:extraction_form_id/preview' => 'extraction_forms#preview'

    # copy a project
    match 'projects/show_copy_form'
    match 'projects/show_copy_request_form'
    match 'projects/request_a_copy'
    match 'projects/copy'
    match 'projects/:project_id/remove_parent_association' => 'projects#remove_parent_association'

    # key questions routes
    match 'key_questions/new' => 'key_questions#new'
    match 'key_questions/show' => 'key_questions#show'
    match 'key_questions/hide' => 'key_questions#hide'
    match 'projects/new/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/new' => 'key_questions#new'
    match 'projects/:project_id/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/:key_question_id/edit' => 'key_questions#edit'

    # getting comment content for all pages
    match 'projects/get_comment_content' => 'comments#show'
    match 'projects/:project_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_content' => 'comments#show'

    match 'projects/get_comment_summary' => 'comments#show_summary'
    match 'get_comment_summary' => 'comments#show_summary'

    # getting comment form from all pages
    match 'projects/get_comment_form' => 'comments#new'
    match 'projects/:project_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_form' => 'comments#new'

    # getting flag form from all pages
    match 'projects/get_flag_form' => 'comments#new_flag'

app/models/adverse_event_column.rb
# == Schema Information
#
# Table name: adverse_event_columns
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  description        :string(255)
#  extraction_form_id :integer
#  created_at         :datetime
#  updated_at         :datetime
#

# This model handles adverse event columns. Adverse event columns are created in the extraction form adverse event section. 
# They cannot be modified by the data extractor.
# The adverse event column is linked to the extraction_form_id, and contains name and description.
class AdverseEventColumn < ActiveRecord::Base
    include GlobalModelMethod

    before_save :clean_string

    belongs_to :extraction_form, :touch=>true
    validates :name, :presence => true

    # check whether a study has been created that uses this extraction_form_arm name.
    # used for alerting users when editing
    # @param [string] id the adverse event column id
    # @return [boolean] whether the adverse event column has data associtated with it
    def self.has_study_data(id)
        @datapoints = AdverseEventResult.where(:column_id => id).all
        if @datapoints.nil? || (@datapoints.length == 0)
            return false
        else
            return true
        end
    end

end

app/controllers/adverse_event_columns_controller.rb
# This controller handles creation and destruction of columns for the adverse events table (in an extraction form).
class AdverseEventColumnsController < ApplicationController

    # Open a new dialog window to create a new adverse event column.
    # Uses views/adverse_event_columns/new.js.erb.
    def new
        @adverse_event_column = AdverseEventColumn.new
        @extraction_form = ExtractionForm.find(params[:extraction_form_id])
        @project = Project.find(params[:project_id])
    end

    # save the new adverse event column.
    # uses views/adverse_event_columns/create.js.erb
    def create
        @adverse_event_column = AdverseEventColumn.new(params[:adverse_event_column])
        if @saved = @adverse_event_column.save
            @extraction_form_adverse_event_columns = AdverseEventColumn.where(:extraction_form_id => @adverse_event_column.extraction_form_id).all
            @extraction_form = ExtractionForm.find(@adverse_event_column.extraction_form_id)
            @project = Project.find(@extraction_form.project_id)
        else
            problem_html = create_error_message_html(@adverse_event_column.errors)
            flash[:modal_error] = problem_html
        end
    end

    # destroy the adverse event column.
    # uses views/adverse_event_columns/destroy.js.erb
    def destroy
        @adverse_event_column = AdverseEventColumn.find(params[:id])
        @extraction_form = ExtractionForm.find(@adverse_event_column.extraction_form_id)
        @project = Project.find(@extraction_form.project_id)
        @has_study_data = AdverseEventColumn.has_study_data(@adverse_event_column.id)
    end

end

app/views/adverse_event_columns/_example_table.html.erb
<% if !@extraction_form_adverse_event_columns.nil? && @extraction_form_adverse_event_columns.length > 0 %>
	<table class="list_table" summary="Table For Editing Adverse Event Columns" id="editing_adverse_event_cols_table">
		<thead>
			<tr>
				<th>
					<label for="Arm or Total">Arm or Total</label>
				</th>
				<th>
					<label for="Arm or Total">Adverse Event Title</label>
				</th>
				<th>
					<label for="Arm or Total">Description</label>
				</th>
					<% for col in @extraction_form_adverse_event_columns %>
						<th class="qtip_col_<%= col.id %>">
							<label for="<%= col.name %>"><%= col.name %></label> 
						</th>
					<% end %>
			</tr>
		</thead>
	</table>
<% else %>

app/views/adverse_event_columns/_form.html.erb
<div id="validation_message_adverse">
<%= render "layouts/modal_info_messages" %>
</div>

<%= form_for @adverse_event_column, :action => :create,  :remote => true, :id => "new_adverse_event_column" do |f| %>
	
	<div class="form_content">
	<%= f.hidden_field :extraction_form_id, :value => @extraction_form.id %>
	<table class='form_table'>
		<tr>
			<td class='label top'>
				<label for="Column Title">Column Title: </label>
			</td>
			<td class='input top'>
				<%= f.text_field :name, :class => "editable_field", :title => "column title" %> 
			</td>
		</tr>
		
		<tr>
			<td class='label'>
				<label for="Description">Description: </label>
			</td>
			<td class='input'>
				<%= f.text_field :description, :class => "editable_field", :title => "adverse event description" %> 
			</td>
		</tr>
	</table>
	<br/><br/><br/><br/>
	<div class="popup-footer actions inline-actions">
		<button type="submit" class="positive" data-disable-with="<%= ajax_wait_msg %>">
			<%= image_tag "Add.png", :alt => "Add" %> Save
		</button><%= render :partial=>'save_indicators/default' %>
		<button class="negative" id="add_adverse_close">
			<%= image_tag "Cancel.png", :alt => "Cancel" %> Cancel
		</button>		
	</div>

<% end %>

<script type="text/javascript">

$("#add_adverse_close").bind("click", function(event)
{
event.preventDefault();
$('#new_adverse_entry').dialog('close');
});

</script>

app/views/adverse_event_columns/_table.html.erb
<table class="classic-a" summary="Table For Editing Adverse Event Columns" id="editing_adverse_event_cols_table">
	<thead>
		<tr>
			<th>
			<label for="Arm or Total">Arm or Total</label>
			</th>
			<th>
			<label for="Arm or Total">Adverse Event Title</label>
			</th>
			<th>
			<label for="Arm or Total">Description</label>
			</th>
			<% for col in @extraction_form_adverse_event_columns %>
				<th class="qtip_col_<%= col.id %>">
					<label for="<%= col.name %>"><%= col.name %></label> 
				<%= link_to image_tag("Silk_cross.png"), adverse_event_column_path(col.id), :method => "delete", :remote => true, :class => "delete_column_link", :style=>"float:right", :alt => "delete this column" %>
				</th>
			<% end %>
		</tr>
	</thead>
</table>
<br/><br/>

<script type="text/javascript">
			<% for col in @extraction_form_adverse_event_columns %>
		
			$('.qtip_col_<%= col.id %>').qtip({
			   content: '<%= col.description %>',
			   show: 'mouseover',
			   hide: 'mouseout',
				  position: {
				  corner: {
					 target: 'bottomMiddle',
					 tooltip: 'topRight'
				  }
			   }
			});
	<% end %>
					
</script>

app/views/adverse_event_columns/create.js.erb
$("#new_adverse_entry").html("<%= escape_javascript(render :partial=>"adverse_event_columns/form") %>");
$("#adverse_event_fields_table").html("<%= escape_javascript(render :partial=>"adverse_event_columns/table") %>");
$("#new_adverse_entry").dialog('close');

$("#saved_item_indicator_adverse").show().delay(500).fadeOut(300);
$("#validation_message_adverse").html("");

app/views/adverse_event_columns/destroy.js.erb
var str = "<%= @has_study_data %>" ;
var has_study_data = (str === 'true');
if(has_study_data)
	{
		var message = "One or more studies have been created that use this data item. Removing this data item will remove it for these studies as well. Are you sure you want to continue?";
		if (confirm(message))
		{
			<% @adverse_event_column.destroy %>
			<% @extraction_form_adverse_event_columns = AdverseEventColumn.where(:extraction_form_id => @extraction_form.id).all %>			
			$("#adverse_event_fields_table").html("<%= escape_javascript(render :partial => "adverse_event_columns/table") %>");
			$("#removed_item_indicator_adverse").show().delay(500).fadeOut(300);
			$("#validation_message_adverse").html("");			
		}
	}
	else{
		var message = "Are you sure you want to delete this column?";
		if (confirm(message))
		{	
			<% @adverse_event_column.destroy %>
			<% @extraction_form_adverse_event_columns = AdverseEventColumn.where(:extraction_form_id => @extraction_form.id).all %>			
			$("#adverse_event_fields_table").html("<%= escape_javascript(render :partial => "adverse_event_columns/table") %>");
			$("#removed_item_indicator_adverse").show().delay(500).fadeOut(300);
			$("#validation_message_adverse").html("");			
		}
	}

app/views/adverse_event_columns/new.js.erb
$("#new_adverse_entry").html("<%= escape_javascript(render :partial=>'adverse_event_columns/form')%>");
$("#new_adverse_entry :button").removeAttr("disabled");
$("#new_adverse_entry").dialog("option", "title", "New Adverse Event Column Title");			
$('#new_adverse_entry').dialog('open');	