config/routes.rb
Srdr::Application.routes.draw do

  get "search_registry" => "registry_usage#search_registry"

    root :to => 'home#index'

    resources :ef_instructions

    resources :comments

    resources :extraction_forms, :study_extraction_forms, :extraction_form_arms, :extraction_form_diagnostic_tests, :extraction_form_adverse_events
    resources :extraction_form_sections, :study_extraction_form_sections
    resources :users, :password_resets,  :user_project_roles, :user_sessions
    resources :quality_rating_fields, :quality_rating_data_points
    resources :adverse_events, :adverse_event_results, :adverse_event_columns
    resources :design_details, :design_detail_fields, :design_detail_data_points
    resources :primary_publications, :primary_publication_numbers, :secondary_publications, :secondary_publication_numbers
    resources :outcome_comparison_results, :outcome_comparison_columns
    resources :quality_dimension_fields, :quality_dimension_data_points
    resources :baseline_characteristics, :baseline_characteristic_fields, :baseline_characteristic_data_points
    resources :arm_details, :arm_detail_fields, :arm_detail_data_points
    resources :outcome_details, :outcome_detail_fields, :outcome_detail_data_points
    resources :quality_details, :quality_detail_fields, :quality_detail_data_points
    resources :diagnostic_test_details, :diagnostic_test_detail_fields, :diagnostic_test_detail_data_points
    resources :arms, :diagnostic_tests
    resources :outcomes, :outcome_columns, :outcome_results, :outcome_timepoints, :extraction_form_outcome_names
    resources :key_questions, :studies_key_questions
    resources :outcome_measures, :outcome_data_points
    resources :comparisons

    resources :studies do
        resources :arms
        get 'data'
        get 'edit_split' => 'studies#edit_split'
    end

    resources :feedback_items

    get "home/index"
    get "user_sessions/new"
    get "primary_publications/get_pubmed_data"
    # ---------- not sure if needed [MK] ---------------
    #get "adv_search/index"

    resource :account, :controller                     => "users"
    get "account/email_preferences"                    => "users#email_preferences"
    post "account/toggle_email_preference/:project_id" => "users#toggle_email_preference"
    post "account/turn_on_all_email_reminders"         => "users#turn_on_all_email_reminders"
    post "account/turn_off_all_email_reminders"        => "users#turn_off_all_email_reminders"

    # ---------- New Audit trail support ---------------
    get "audit_trails/new"

    # ---------- DAA Info page ------------
    get  "daa/info"                => "daa_info#info"
    get  "daa/eligibility"         => "daa_info#eligibility"
    get  "daa/not_eligible"        => "daa_info#not_eligible"
    post "daa/eligible"            => "daa_info#eligible"
    post "daa/create_participant"  => "daa_info#create"

    # --------- DAA Consent form ----------
    get  "daa/consent"      => "daa_info#consent"
    get  "daa/thanks"       => "daa_info#consent_thanks"
    get  "daa/consent_form" => "daa_info#consent_form"
    post "daa/consent"      => "daa_info#consent_submit"

    # ---------- EPC Questionnaire ----------
    get "questionnaire/form" => "bryant_form#form"
    post "questionnaire/save" => "bryant_form#save"

    # hiding the ahrq header
    match '/application/go_full_screen' => 'application#toggle_ahrq_header'

    # used for adding and removing extraction forms to and from studies
    match 'projects/api_index_published' => 'projects#api_index_published'
    match 'projects/published' => 'projects#published'
    match 'home/quarterly_training'
    match 'home/external_resources'
    match 'register' => 'users#new'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'register/confirmation' => 'users#confirmation'
    match 'register/reviewconfirmation' => 'users#reviewconfirmation'
    match 'register/error' => 'users#error'
    match 'register/agreement_error' => 'users#agreement_error'
    match 'account/validation.html' => 'users#validateuser'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'projects/:project_id/studies/extraction_form_add' => 'studies#extraction_form_add'
    match 'projects/:project_id/studies/extraction_form_remove' => 'studies#extraction_form_remove'
    match 'projects/:project_id/studies/:id/extraction_form_add' => 'studies#extraction_form_add_edit'
    match 'projects/:project_id/studies/:id/extraction_form_remove' => 'studies#extraction_form_remove_edit'
    match 'projects/:id/extraction_forms' => 'projects#extractionforms'
    match 'projects/:project_id/extraction_forms/new' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/arms' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/:id' => 'extraction_forms#show'
    match 'projects/:project_id/extraction_forms/:extraction_form_id/import' => 'extraction_form_section_copies#import_from_previous_forms'
    match 'extraction_form_section_copies/save_import_request'

    match 'projects/:id/studies' => 'projects#studies'
    match 'projects/:id/users' => 'projects#users'
    match 'projects/:id/review' => 'projects#review'
    match 'projects/:id/publish' => 'projects#publish'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120204 - added support for table creator
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/tablecreator' => 'tablecreator#index'
    match 'tablecreator/buildtable' => 'tablecreator#buildtable'
    match 'tablecreator/templatemanager' => 'tablecreator#templatemanager'
    match 'projects/tablecreator/templatemanager' => 'tablecreator#templatemanager'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20121004 - added support for export tools
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/exporttools' => 'exporttools#index'
    match 'projects/exporttools/simpleexport' => 'exporttools#simpleexport'
    match 'projects/exporttools/advexport' => 'exporttools#advexport'
    match 'projects/exporttools/reportbuilder' => 'exporttools#reportbuilder'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120316 - added support for comparing studies - aka double extraction
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/:id/create_consensus' => 'studyconsensus#createconsensus'
    match 'comparestudies/create_consensus' => 'studyconsensus#createconsensus'
    match '/compexporter/saveas_excel/:project_id'=>'studyconsensus#export_to_excel'

    # used for adding extraction forms to project key questions
    #match 'extraction_forms/assign_key_questions' => 'extraction_forms#assign_key_questions'
    resources :projects do
        resources :studies do
            resources :arms, :secondary_publications, :primary_publications
            resources :extraction_forms do
                resources :outcome_measures do
                    post :edit, :save, :cancel
                    delete :destroy
                end
                resources :outcome_timepoints do
                    post :edit, :save, :cancel
                    delete :destroy_modal
                    delete :destroy
                end
            end
        end
        resources :extraction_forms
        resources :key_questions
    end

    match 'forgot_password' => 'password_resets#new'

    match 'projects/cancel_new' => 'projects#cancel_new'
    # match 'projects/:id/studies' => 'studies#index'

    match 'projects/:project_id/extraction_forms/:extraction_form_id/preview' => 'extraction_forms#preview'

    # copy a project
    match 'projects/show_copy_form'
    match 'projects/show_copy_request_form'
    match 'projects/request_a_copy'
    match 'projects/copy'
    match 'projects/:project_id/remove_parent_association' => 'projects#remove_parent_association'

    # key questions routes
    match 'key_questions/new' => 'key_questions#new'
    match 'key_questions/show' => 'key_questions#show'
    match 'key_questions/hide' => 'key_questions#hide'
    match 'projects/new/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/new' => 'key_questions#new'
    match 'projects/:project_id/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/:key_question_id/edit' => 'key_questions#edit'

    # getting comment content for all pages
    match 'projects/get_comment_content' => 'comments#show'
    match 'projects/:project_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_content' => 'comments#show'

    match 'projects/get_comment_summary' => 'comments#show_summary'
    match 'get_comment_summary' => 'comments#show_summary'

    # getting comment form from all pages
    match 'projects/get_comment_form' => 'comments#new'
    match 'projects/:project_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_form' => 'comments#new'

    # getting flag form from all pages
    match 'projects/get_flag_form' => 'comments#new_flag'

app/controllers/home_controller.rb
# this controller handles showing of main srdr pages
class HomeController < ApplicationController
  layout :determined_by_request
  before_filter :require_admin, :only=>[:user_list]

  # "srdr home" -
  # show SRDR main page
  def index
     @user_session = UserSession.new
     # Load recently completed reports
     @recent_reports = Recentreports.new
     @mostviewed_reports = Mostviewedreports.new
     @events = Srdrevents.new
     session[:items_per_page] = session[:items_per_page].nil? ? 10 : session[:items_per_page]
  end

  def blog
  end

  # for all users, show the about srdr page
  def about
  end

  # show help page
  def help
    @selected = params[:selected].nil? ? 0 : params[:selected]
  end

  # show srdr policies
  def policies
  end

  # CSS DESIGN TESTING
  def css_markup
    render :layout=>false
  end

  def css_markup_home
    render :layout=>false
  end

  # show the feedback form page
  def feedback
    render 'feedback_items/feedback_form'
  end

  def user_list
    @users = User.find(:all, :order=>"lname ASC");
  end

  # submit a user's feedback to the database
  def send_feedback
    feedback = FeedbackItem.new(:user_id=>current_user.id, :url=>params[:url], :page=>params["feedback-form-select"], :description=>params[:description])
    if @saved = feedback.save
        flash[:success_message] = "Thank you for your feedback. We will inform you when this issue has been resolved."
    else
        flash[:error_message] = "We're sorry, but we could not complete this request. Please send an email to cparkin@tuftsmedicalcenter.org with a description of the problem."
    end
    render 'feedback_items/feedback_submit.js.erb'
  end
  # a basic 'coming soon' page
  def coming_soon
    respond_to do |format|
      format.js{ render "coming_soon.js.erb"}
      format.html{ render "coming_soon.html.erb"}
    end
  end
  # show demo video 1
  def demo1
  end

  # show demo video 2
  def demo2
  end

  # show demo video 3
  def demo3
  end

 protected
 # show layout depending on type of request - i.e. don't show full header for ajax requests
 def determined_by_request
   if request.xhr?
     return false
   else
     'application'
   end
 end


end

app/views/home/_mostviewed_list.html.erb
<table class="list_table" style='border:none;'>
<%
    max_2_display = @mostviewed_reports.size()
    if max_2_display > 3
        max_2_display = 3
    end
    for idx in (0..max_2_display - 1)
        access_state = "Public Report"
        access_label = "Complete"
        num_studies = @mostviewed_reports.getNumStudies(idx)
        num_key_qs = @mostviewed_reports.getNumKeyQuestions(idx)
        num_ext_forms = @mostviewed_reports.getNumExtractionForms(idx)
        report_date = @mostviewed_reports.getDate(idx)
        report_desc = @mostviewed_reports.getDescription(idx)
%>
    <tr>
        <td class='data' style='position:relative;'>
            <span style='float:left;'>
               <h2><%= @mostviewed_reports.getTitle(idx) %></h2><br/>
            </span>
            <span style='float:right;position:relative; right:30px; top:0px;' class='status'>
                <%= access_state %> 
                <span class="<%= access_label.downcase %>"><%= access_label %></span>
            </span>
            <br clear='all'>
            <span class='bold'>Statistics:</span> <%= pluralize(num_studies, 'Study') %>,
            <%= pluralize(num_key_qs, 'Key Question') %>,
            <%= pluralize(num_ext_forms, 'Extraction Form') %>,    
            <%# Project.get_status_string(project.id) %><br/>
            <span class='bold'>Date Created: </span><%= report_date.strftime("%b %d, %Y %I:%M%p") %><br/>
            <span class='bold'>Description: </span><%= report_desc.empty? ? "None Provided" : report_desc %>
        </td>
    </tr>
<%
    end
%>
</table>

app/views/home/_recent_list.html.erb
<table class="list_table" style='border:none;'>
<%
    max_2_display = @recent_reports.size()
    if max_2_display > 3
        max_2_display = 3
    end
    for idx in (0..max_2_display - 1)
        access_state = "Public Report"
        access_label = "Complete"
        num_studies = @recent_reports.getNumStudies(idx)
        num_key_qs = @recent_reports.getNumKeyQuestions(idx)
        num_ext_forms = @recent_reports.getNumExtractionForms(idx)
        report_date = @recent_reports.getDate(idx)
        report_desc = @recent_reports.getDescription(idx)
%>
    <tr>
        <td class='data' style='position:relative;'>
            <span style='float:left;'>
               <h2><%= @recent_reports.getTitle(idx) %></h2><br/>
            </span>
            <span style='float:right;position:relative; right:30px; top:0px;' class='status'>
                <%= access_state %> 
                <span class="<%= access_label.downcase %>"><%= access_label %></span>
            </span>
            <br clear='all'>
            <span class='bold'>Statistics:</span> <%= pluralize(num_studies, 'Study') %>,
            <%= pluralize(num_key_qs, 'Key Question') %>,
            <%= pluralize(num_ext_forms, 'Extraction Form') %>,    
            <%# Project.get_status_string(project.id) %><br/>
            <span class='bold'>Date Created: </span><%= report_date.strftime("%b %d, %Y %I:%M%p") %><br/>
            <span class='bold'>Description: </span><%= report_desc.empty? ? "None Provided" : report_desc %>
        </td>
    </tr>
<%
    end
%>
</table>

app/views/home/coming_soon.js.erb
$("#content").html("<h2>Coming Soon</h2><br/><br/>Check back soon for updates!");

app/views/home/datasharingpolicy.html.erb
<div class="document_title">SRDR Data Sharing Policy</div><p/>&nbsp;<p/>&nbsp;<p/>&nbsp;The SRDR is committed to keeping all Systematic Review projects Open Access (with Creative Commons Licence as fully Open Access on srdr.ahrq.gov). <p/>&nbsp;<p/>&nbsp;The full text of all Systematic Review projects, including an individual project's study abstraction templates and data, is immediately accessible on srdr.ahrq.gov when made public (i.e., when a project's status is updated from 'private report incomplete' to 'public report complete'). All projects published in the SRDR do not require a copyright statement and will be published under a Creative Commons license (Creative Commons, attribution, non-commercial; http://creativecommons.org/licenses/by-nc/3.0/), which allows full reuse for non-commercial purposes with full attribution. <p/>&nbsp;<p/>&nbsp;Open access projects can be identified by the following Creative Commons copyright notice appearing at the top of all project-associated Web pages:<p/>&nbsp;<p/>&nbsp;"This is an open-access article distributed under the terms of the Creative Commons Attribution Non-commercial License, which permits use, distribution, and reproduction in any medium, provided the original work is properly cited, the use is non commercial and is otherwise in compliance with the license. See: http://creativecommons.org/licenses/by-nc/3.0/ and http://creativecommons.org/licenses/by-nc/3.0/legalcode."

app/views/home/index.html.erb
<% content_for :title, content='Home' %>

<%
    # Get and set bread crumb to current page
    urlhistory = Breadcrumb.new
    urlhistory.setCurrentPage("Home","Home","/")
    session[:urlhistory] = urlhistory

    # Get site properties
    siteproperties = session[:guiproperties]
    siteproperties = nil
    if siteproperties.nil?
        siteproperties = Guiproperties.new
        session[:guiproperties] = siteproperties
    end
%>
<!--################################################################ -->
<!-- THE HOMEPAGE COLLAGE AND LOGIN SECTION                          -->
<!--#################################################################-->

<!-- Overwrite container background in layout/application. We need this background for the rest of the app but on the home page it's ugly. -->
<style>
  div#container { background: none; !important }
</style>


<div id="homepage-collage-div">
    <!--<img alt="" src="images/homepage/hero_txt_welcome.gif" width=359 height=69 style='position:absolute; top:20px; left:20px;z-index:100'/>-->
    <div style='position:absolute; top:20px; left:20px; z-index:100; color: #045d9a; font-size:35px; font-family:Helvetica, Arial, sans-serif;line-height:40px;text-shadow: #045d9a .05em .05em .1em;'>
        Welcome to the Systematic<br/>Review Data Repository
    </div>
    <img alt="Welcome to the Systematic Review Data Repository" src="/images/homepage/homepage_collage.jpg" alt='Welcome to the Systematic Review Data Repository' style="position:absolute;right:0px;top:0px;height:100%;z-index:99"/>

    <div id="welcome-text" >
        The Systematic Review Data Repository (SRDR) is a powerful and easy-to-use tool for the extraction and management of data for systematic 
        review or meta-analysis. It is also an open and searchable archive of systematic reviews and their data.

        <div id='announcement-introjs' style='color: white; background: #fd4444; padding: 5px; width: 126px; border-radius: 3px;'>
          <%= link_to 'New Announcement', '/blog', style: 'color: white;' %>
        </div>

        <!--
          <div class='actions'>
            <button class="positive" id="training_button">
              RSVP Today for SRDR Training Webinars! <%= image_tag "Silk_bullet_go.png", :alt => "Continue to Training Information" %>
            </button>
            <button class="positive" id="training_button">
              <%# image_tag "Silk_bullet_go.png", :alt => "Get Assistance over the Holidays" %> Need Assistance During the Holidays?
            </button>
          </div>
        -->

        <!--div class='announcement'>
            Scheduled maintenance in <span id='dayCntr'></span> day(s).<br>
            <span id='introjs' class='tiny'>Click me for more details.</span><br>
        </div-->

    </div> <!-- END <div id="welcome-text" > -->

    <div id='login-window'>
        <div id='login-div'>
            To contribute data or comment on deposited projects, simply <%= link_to "Register", register_path, {:title=>"Register for a new account", :class=>'register_link'} %> for an account.<br/><br/><br/>
            <div id='login_form_div'>
                <%  if !defined?(current_user) || current_user.nil? %>
                    <%= render "user_sessions/login_form", :locals => {:user_session => @user_session} %>
                <% else %>
                    Account Details: <br/><br/>
                    You are logged in as <%= current_user.login %> <%# request.session_options[:id] %>
                <% end %>
            </div>
        </div>
    </div>
    <%= link_to "Forgot Password?", "#", html_options = {style:'position:absolute; bottom:10px; right:10px;'} %>
</div>
<!--################################################################ -->
<!-- THE HOMEPAGE CONTENT SECTION                                    -->
<!--#################################################################-->
<div id='home-content' style='border-bottom: none;'>
    <!-- THE LEFT PANEL OF RECENT SUBMISSIONS -->
    <div id="home-left-panel" style='margin-bottom: 250px;'>
        <table width="100%">
            <tr>
                <td align="LEFT">
                <h2>Recently Completed and Deposited Reports Data</h2>
                </td>
            </tr>
            <tr>
                <td align="LEFT">
                <%= render 'reports_tabs' %>
                </td>
            </tr>
        </table>
        <p/><br/>
        <%= render 'shared/creative_commons_note' %>
    </div>
    <div id="home-right-panel">
        <h2>Popular Resources</h2>
        <div class='hr'></div>
        <ul class='link_list popular-resources'>
          <li style='height: auto;'><%= link_to "About SRDR", about_path, html_options = { title: 'Learn about SRDR' } %> </li>
          <li style='height: auto;'><%= link_to "PROSPERO: International prospective register of systematic reviews", "https://www.crd.york.ac.uk/prospero", html_options = { class: "needs_exit_disclaimer", target: "_blank" } %></li>
          <li style='height: auto;'><%= link_to "The EQUATOR Network: Enhancing the QUAlity and Transparency Of health Research", "http://www.equator-network.org", html_options = { class: "needs_exit_disclaimer", target: "_blank" } %></li>
          <li style='height: auto;'><%= link_to "AHRQ Methods Guide for Effectiveness and Comparative Effectiveness Reviews", "https://effectivehealthcare.ahrq.gov/index.cfm/search-for-guides-reviews-and-reports/?productid=318&pageaction=displayproduct", html_options = { class: "needs_exit_disclaimer", target: "_blank" } %></li>
          <li style='height: auto;'><%= link_to "Cochrane Handbook for Systematic Reviews of Interventions", "http://handbook.cochrane.org", html_options = { class: "needs_exit_disclaimer", target: "_blank" } %></li>
          <li style='height: auto;'><%= link_to "AHRQ Proposed Governance and Data Management Policy for the Systematic Review Data Repository (SRDR)", "https://effectivehealthcare.ahrq.gov/index.cfm/search-for-guides-reviews-and-reports/?pageaction=displayproduct&productid=1266", html_options = { class: "needs_exit_disclaimer", target: "_blank" } %></li>
          <li style='height: auto;'><%= link_to "The COMET Initiative", "http://www.comet-initiative.org", html_options = { class: "needs_exit_disclaimer", target: "_blank" } %></li>
          <li style='height: auto;'>Check back soon for additional features.</li>
        </ul>
        <br/><br/>
        <h2>Help</h2>
        <div class='hr'></div>
        <br/>
        <ul class='link_list'>
            <li>
                <%= link_to "Visit the Help Pages and User Manual", help_path, html_options = { title: "Visit the Help Pages and User Manual"} %>
            <li>
        </ul>

        <h2 data-intro='SRDR+ now available!' data-step='1'>SRDR Announcements</h2>
        <div class='hr'></div>
        <br/>
        <ul style='margin-bottom: 60px;' class='link_list'>
            <li>
                <!--span style='background: red; padding: 2px; color: white; font-weight: bold; border-radius: 10px;'>
                    New
                </span-->
                SRDR+, the new version of SRDR, is now available! Click <a href='https://srdrplus.ahrq.gov' class='needs_exit_disclaimer' target='_blank'>here</a> to try out the new version. Your projects will be migrated to SRDR+ soon (we’ll keep you posted). In the meantime, feel free to check out its new features!
            </li>

<!--
            <%# if siteproperties.isSiteTypeProduction() %>

            <li>
                The <a href='<%#= siteproperties.getTrainingSiteURL() %>' target='_blank'>SRDR Training Site</a> is now available
            </li><br/><br/>

            <%# end %>

            <li>
                Our first <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3351737/" class='needs_exit_disclaimer' target="_blank">SRDR publication <img alt="WARNING: This link will direct you away form our site." src="/images/exit_disclaimer.gif"/></a> has been published!
            </li>

            Check out the new External Resources<br />
            tab on the <%#= link_to "SRDR Help and Training page", help_path %>
            for links to recommended systematic<br />
            review reference materials, including:<br />
            published works, video series, and online resources.
-->
        </ul>

        <br />

        <h2>Statistics</h2>
        <div class='hr'></div>
        <br/>
        <ul class='link_list'>
            <li><strong>Registered Users: </strong><%= User.count - 1 %></li>
            <li><strong>Projects In Progress: </strong><%= Project.count %></li>
        </ul>

        <br/>
        <!--h2 data-intro="Here you will find all available information regarding planned outages. We will do our best to post information as soon as possible so you can plan ahead and schedule accordingly." data-step='0'>Maintenance Schedule</h2-->
        <h2>Maintenance Schedule</h2>
        <div class='hr'></div>
        <br/>
            <ul class='link_list'>
                <li>There is no maintenance scheduled as of <%= Time.now.strftime("%m/%d/%Y") %></li>
            </ul>
            <!-- <ul class='link_list'>
                <li><strong>Maintenance scheduled for Sunday, September 29th, 2013.</strong></li>
                <br/>
                <li>Starting at 10:00am EST the SRDR servers will be undergoing scheduled maintenance. The site will be unavailable for an estimated 2 hours. We apologize for any inconvenience this may cause.</li>
            </ul> -->
        <br/>
        <span id='page_end'></span>
        <!--This graphic notice, <img alt="WARNING: This link will redirect you away from our site." src='/images/exit_disclaimer.gif'>, indicates that you are leaving this Federal Government Web site.  <a href='https://www.ahrq.gov/exitdisclaimer.htm' target='_blank'>Learn more</a>
        <br/><br/><br/>&nbsp;-->
        <!--
        <table width="100%">
            <tr>
                <td align="LEFT">
                <h2>Popular Resources</h2>
                </td>
            </tr>
            <tr>
                <td align="LEFT">
                <%= render 'srdr_events' %>
                </td>
            </tr>
        </table>
         -->
    </div>
</div>
<script type='text/javascript'>
//<!--
function index_init() {
  try{
    checkLoaded(); // HOLD OFF UNTIL THE LAST ELEMENT IS LOADED
    set_index_js();
  } catch( err ) {
    setTimeout('index_init()', 200);
  }
}
function checkLoaded() {
    if ( $('#page_end').length == 0) $jquery.error( 'not ready' );
}
function set_index_js(){
    $("#forgot_password").unbind();
    $("#forgot_password").bind("click",function(event){
        event.preventDefault();
        window.location.replace("/forgot_password");
    });

    // add a pop-up notifier for any links that are in need of an exit disclaimer
    $(".needs_exit_disclaimer").unbind();
    $(".needs_exit_disclaimer").live("click",function(event){
        event.preventDefault();
        var url = $(this).attr("href");
        $("#exiting_modal").dialog({
            resizable: false,
            title: "Exit Disclaimer",
            width: 550,
            modal: true,
            buttons:{
                "Return to SRDR":function(){
                    $(this).dialog("close");
                },
                "Continue to External Site": function(){
                    $(this).dialog("close");
                    window.open(url,"_blank");
                    //document.location.href = $(this).attr("href");
                }
            }
        })
    });
    $("#training_button").unbind();
    $("#training_button").bind("click",function(event){
        //window.location.assign("/home/training_sessions");
        window.location.assign("/help?selected=6");
    });
}
index_init();


;COUNTDOWN = {

  getDaysUntilMaintenance: function(){

    var today = new Date();
    var maintenanceDate = new Date();

    // Set maintenance date. Months are 0 indexed.
    maintenanceDate.setFullYear(2017,10-1,29);

    // Use get time to get milliseconds since epoch.
    var msToday = today.getTime();
    var msMaintenanceDate = maintenanceDate.getTime();

    // Get difference.
    var msDayDelta = msMaintenanceDate - msToday;

    // Do some conversion
    var seconds = msDayDelta/1000;
    var minutes = seconds/60
    var hours = minutes/60
    var days = Math.floor(hours/24);

    return days;
  },
  updateHtml: function(days){
    // Insert the result.
    $('span#dayCntr').text(days);
    $('div.announcement').css({"font-size":"1.3em", "color":"red"})
    $('span.tiny').css({"font-size":"0.8em", "color":"red"})
  },
  showMaintenanceAnnouncement: function(){
    $('div.announcement').show();
  },
  hideMaintenanceAnnouncement: function(){
    $('div.announcement').hide();
  },
  highlightAnnouncement: function(){
    $('div.announcement').effect("highlight", {}, 3000);
  },
};

$(document).ready(function() {

  // Set days until maintenance.
  var days = COUNTDOWN.getDaysUntilMaintenance();

  COUNTDOWN.updateHtml(days);
  if (days<0)
    {
    COUNTDOWN.hideMaintenanceAnnouncement();
    }
  else if (days<7)
    {
    COUNTDOWN.showMaintenanceAnnouncement();
    COUNTDOWN.highlightAnnouncement();
    }
  else
    {
    COUNTDOWN.hideMaintenanceAnnouncement();
    }

  $('span#introjs').on( "click", function() {
    introJs().start();
  })

    //$( 'div#announcement-introjs' ).on( 'click', function() {
    //    introJs().start();
    //})
});

    
//-->
</script>