config/routes.rb
Srdr::Application.routes.draw do

  get "search_registry" => "registry_usage#search_registry"

    root :to => 'home#index'

    resources :ef_instructions

    resources :comments

    resources :extraction_forms, :study_extraction_forms, :extraction_form_arms, :extraction_form_diagnostic_tests, :extraction_form_adverse_events
    resources :extraction_form_sections, :study_extraction_form_sections
    resources :users, :password_resets,  :user_project_roles, :user_sessions
    resources :quality_rating_fields, :quality_rating_data_points
    resources :adverse_events, :adverse_event_results, :adverse_event_columns
    resources :design_details, :design_detail_fields, :design_detail_data_points
    resources :primary_publications, :primary_publication_numbers, :secondary_publications, :secondary_publication_numbers
    resources :outcome_comparison_results, :outcome_comparison_columns
    resources :quality_dimension_fields, :quality_dimension_data_points
    resources :baseline_characteristics, :baseline_characteristic_fields, :baseline_characteristic_data_points
    resources :arm_details, :arm_detail_fields, :arm_detail_data_points
    resources :outcome_details, :outcome_detail_fields, :outcome_detail_data_points
    resources :quality_details, :quality_detail_fields, :quality_detail_data_points
    resources :diagnostic_test_details, :diagnostic_test_detail_fields, :diagnostic_test_detail_data_points
    resources :arms, :diagnostic_tests
    resources :outcomes, :outcome_columns, :outcome_results, :outcome_timepoints, :extraction_form_outcome_names
    resources :key_questions, :studies_key_questions
    resources :outcome_measures, :outcome_data_points
    resources :comparisons

    resources :studies do
        resources :arms
        get 'data'
        get 'edit_split' => 'studies#edit_split'
    end

    resources :feedback_items

    get "home/index"
    get "user_sessions/new"
    get "primary_publications/get_pubmed_data"
    # ---------- not sure if needed [MK] ---------------
    #get "adv_search/index"

    resource :account, :controller                     => "users"
    get "account/email_preferences"                    => "users#email_preferences"
    post "account/toggle_email_preference/:project_id" => "users#toggle_email_preference"
    post "account/turn_on_all_email_reminders"         => "users#turn_on_all_email_reminders"
    post "account/turn_off_all_email_reminders"        => "users#turn_off_all_email_reminders"

    # ---------- New Audit trail support ---------------
    get "audit_trails/new"

    # ---------- DAA Info page ------------
    get  "daa/info"                => "daa_info#info"
    get  "daa/eligibility"         => "daa_info#eligibility"
    get  "daa/not_eligible"        => "daa_info#not_eligible"
    post "daa/eligible"            => "daa_info#eligible"
    post "daa/create_participant"  => "daa_info#create"

    # --------- DAA Consent form ----------
    get  "daa/consent"      => "daa_info#consent"
    get  "daa/thanks"       => "daa_info#consent_thanks"
    get  "daa/consent_form" => "daa_info#consent_form"
    post "daa/consent"      => "daa_info#consent_submit"

    # ---------- EPC Questionnaire ----------
    get "questionnaire/form" => "bryant_form#form"
    post "questionnaire/save" => "bryant_form#save"

    # hiding the ahrq header
    match '/application/go_full_screen' => 'application#toggle_ahrq_header'

    # used for adding and removing extraction forms to and from studies
    match 'projects/api_index_published' => 'projects#api_index_published'
    match 'projects/published' => 'projects#published'
    match 'home/quarterly_training'
    match 'home/external_resources'
    match 'register' => 'users#new'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'register/confirmation' => 'users#confirmation'
    match 'register/reviewconfirmation' => 'users#reviewconfirmation'
    match 'register/error' => 'users#error'
    match 'register/agreement_error' => 'users#agreement_error'
    match 'account/validation.html' => 'users#validateuser'
    # MK Registration confirmation re-directs -----------------------------------------------
    match 'projects/:project_id/studies/extraction_form_add' => 'studies#extraction_form_add'
    match 'projects/:project_id/studies/extraction_form_remove' => 'studies#extraction_form_remove'
    match 'projects/:project_id/studies/:id/extraction_form_add' => 'studies#extraction_form_add_edit'
    match 'projects/:project_id/studies/:id/extraction_form_remove' => 'studies#extraction_form_remove_edit'
    match 'projects/:id/extraction_forms' => 'projects#extractionforms'
    match 'projects/:project_id/extraction_forms/new' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/arms' => 'extraction_forms#new'
    match 'projects/:project_id/extraction_forms/:id' => 'extraction_forms#show'
    match 'projects/:project_id/extraction_forms/:extraction_form_id/import' => 'extraction_form_section_copies#import_from_previous_forms'
    match 'extraction_form_section_copies/save_import_request'

    match 'projects/:id/studies' => 'projects#studies'
    match 'projects/:id/users' => 'projects#users'
    match 'projects/:id/review' => 'projects#review'
    match 'projects/:id/publish' => 'projects#publish'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120204 - added support for table creator
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/tablecreator' => 'tablecreator#index'
    match 'tablecreator/buildtable' => 'tablecreator#buildtable'
    match 'tablecreator/templatemanager' => 'tablecreator#templatemanager'
    match 'projects/tablecreator/templatemanager' => 'tablecreator#templatemanager'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20121004 - added support for export tools
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/exporttools' => 'exporttools#index'
    match 'projects/exporttools/simpleexport' => 'exporttools#simpleexport'
    match 'projects/exporttools/advexport' => 'exporttools#advexport'
    match 'projects/exporttools/reportbuilder' => 'exporttools#reportbuilder'
    #------------------------------------------------------------------------------------------------------------------------------------
    # [MK] 20120316 - added support for comparing studies - aka double extraction
    #------------------------------------------------------------------------------------------------------------------------------------
    match 'projects/:id/create_consensus' => 'studyconsensus#createconsensus'
    match 'comparestudies/create_consensus' => 'studyconsensus#createconsensus'
    match '/compexporter/saveas_excel/:project_id'=>'studyconsensus#export_to_excel'

    # used for adding extraction forms to project key questions
    #match 'extraction_forms/assign_key_questions' => 'extraction_forms#assign_key_questions'
    resources :projects do
        resources :studies do
            resources :arms, :secondary_publications, :primary_publications
            resources :extraction_forms do
                resources :outcome_measures do
                    post :edit, :save, :cancel
                    delete :destroy
                end
                resources :outcome_timepoints do
                    post :edit, :save, :cancel
                    delete :destroy_modal
                    delete :destroy
                end
            end
        end
        resources :extraction_forms
        resources :key_questions
    end

    match 'forgot_password' => 'password_resets#new'

    match 'projects/cancel_new' => 'projects#cancel_new'
    # match 'projects/:id/studies' => 'studies#index'

    match 'projects/:project_id/extraction_forms/:extraction_form_id/preview' => 'extraction_forms#preview'

    # copy a project
    match 'projects/show_copy_form'
    match 'projects/show_copy_request_form'
    match 'projects/request_a_copy'
    match 'projects/copy'
    match 'projects/:project_id/remove_parent_association' => 'projects#remove_parent_association'

    # key questions routes
    match 'key_questions/new' => 'key_questions#new'
    match 'key_questions/show' => 'key_questions#show'
    match 'key_questions/hide' => 'key_questions#hide'
    match 'projects/new/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/new' => 'key_questions#new'
    match 'projects/:project_id/key_questions/show' => 'key_questions#show'
    match 'projects/new/key_questions/:key_question_id/edit' => 'key_questions#edit'

    # getting comment content for all pages
    match 'projects/get_comment_content' => 'comments#show'
    match 'projects/:project_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/get_comment_content' => 'comments#show'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_content' => 'comments#show'

    match 'projects/get_comment_summary' => 'comments#show_summary'
    match 'get_comment_summary' => 'comments#show_summary'

    # getting comment form from all pages
    match 'projects/get_comment_form' => 'comments#new'
    match 'projects/:project_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/get_comment_form' => 'comments#new'
    match 'projects/:project_id/studies/:study_id/extraction_forms/:extraction_form_id/get_comment_form' => 'comments#new'

    # getting flag form from all pages
    match 'projects/get_flag_form' => 'comments#new_flag'

app/views/studies/_citation_info.html.erb
<% if !@study.id.nil?  %>
	<% details = Study.get_page_header_details(@study.id)%>
	<% citation_study_id = @study.id %>
	<% citation_author = details[0].nil? ? "" : details[0] %>
	<% citation_title = details[1].nil? ? "" : details[1] %>
	<% citation_year = details[2].nil? ? "" : details[2] %>
	<% citation_journal = details[3].nil? ? "" : details[3] %>
	<% citation_volume = details[4].nil? ? "" : details[4] %>
	<% citation_issue = details[5].nil? ? "" : details[5] %>
<% end %>

<% bad = ["-- Not Found --", "", " ",nil] %>
<% if !(bad.include?(citation_title) && bad.include?(citation_author) && bad.include?(citation_year) && bad.include?(citation_journal)) %>
	
	<div class="study_citation">
		<div class="label inline">
		Current Study:
		</div>
		<%= citation_author %> <em><%= citation_title %></em><%= "(#{citation_year})" %>
		<%= citation_journal %> 
		
		<% if !(bad.include?(citation_volume))%>
			<%= "Vol. " + citation_volume %> 
		<% end %>
		<% if !(bad.include?(citation_issue)) %>
			<%= "Issue " + citation_issue %>
		<% end %>
	</div>
<% else %>
	<div class="study_citation">
		<div class="label inline">
			Current Study:
		</div>
		No Primary Publication Specified
	</div>
<% end %>

app/views/studies/_current_extraction_forms.html.erb
<div class="indent_block">			
			<ul>
		<% if !@ext_forms_list.nil? && @ext_forms_list.length > 0 %>
			<% i = 0 %>
		  <% for list_item in @ext_forms_list %>
				<li>
					<% @item = ExtractionForm.find(list_item) %>
					<%= @item.title %>
					<% if !@ext_form_notes[i].nil? && @ext_form_notes[i] != "" %>
						(<%= @ext_form_notes[i] %>)
					<% end %>
					<%= link_to image_tag("Bin_closed.png", :style => "border:0;vertical-align:text-top"), {:controller => :studies, :action => "extraction_form_remove", :number => i, :ext_forms_list => ActiveSupport::JSON.encode(@ext_forms_list), :ext_form_notes => ActiveSupport::JSON.encode(@ext_form_notes)}, :remote => true, :class => "tooltip_delete_extform" %>
				</li>
				<% i = i + 1 %>
		  <% end %>
		  <% else %>
			There are currently no extraction forms associated with this study. Use the form below to add extraction forms to associate with this study.
		  <% end %>
		  </ul>
		  
</div>

app/views/studies/_page_title.html.erb
<% @project = Project.find(params[:project_id]) %>
<% if defined?(@project) && !@project.nil? %>
	<h1>Editing Study in Project: <%= @project.title %>
		<div class="status">(Project Status: Incomplete and Private)</div>
	</h1>
<% else %>
	<h1>Editing Study</h1>
<% end %>

<div id="study_citation_info">
<%= render "studies/citation_info" %>
</div>

<hr/>
<h2>
	<%# if the a local variable named page_title is passed in, use it %>
	<% if !defined?(page_title) %>
		<% page_title = get_page_title %>
	<%# otherwise, get it from the url (application helper) %>
	<% else %>
		<%= get_page_title %>
	<% end %>
</h2>

<%= render "studies/study_buttons" %>

<center>
<span class="unsaved_div" style="display:none; color:red; font: 12px verdana;">
	Please remember to save your changes before leaving this page.
</span>
</center>

app/views/studies/_section_complete_status.html.erb
<% status = "---" %>
<center>
<br/><br/>
<hr width="100%" color="#cccccc">
<br/><br/>
	<div style='width:70%; background-color: #e4e4e4; padding: 10px; text-align: center; border: solid 1px gray;'>
<% unless session[:completed_sections].keys.empty? %>
  <% status = session[:completed_sections][section] %>
  <% status = status.nil? ? "Incomplete" : status[0] == true ? "Complete" : "Incomplete" %>
  	<strong>Section Status:</strong> <span id="<%= section %>_status" style='font-weight: bold !important; color: <%= status == 'Complete' ? 'green' : 'red' %>;'><%= status %></span>
  
<% else %>
  	<strong>Section Status:</strong> <span id="<%= section %>_status" style='font-weight: bold; color: red;'>Incomplete</span>
<% end %>
<br/><br/>
<button type="submit" class="positive toggle_section_button" id="toggle_<%= section %>_button" section="<%= section %>" alt="Click to toggle the selected section">Mark Section <%= status == "Complete" ? "Incomplete" : "Complete" %></button><br/>
</div>
</center><br/><br/>

app/views/studies/_study_buttons.html.erb
<br/>
		<div class="actions centered" id="study_buttons">
			<% if !@study.id.nil? %>
			<%= link_to image_tag("Note_go.png", :style=>"border-style:none;vertical-align:middle;") + " View Study Preview", {}, :id => "view_preview_btn", :class => "positive" %>
			<% end %>
		</div>
		
		<div class="centered"><a href="#studynav" class="small_link">Access Study Navigation</a></div>
		
		<div id="preview_div">
			<br/><br/><br/>
			<center><img src='/images/loading_gif.gif' alt='Loading...'></center>
		</div>
					<% if !@study.id.nil? %>
					<% @project = Project.find(params[:project_id]) %>
		<script type="text/javascript">
		$("#preview_div").dialog({
			autoOpen: false,
			minWidth: 900,
			height: 650,
			position: 'top',
			resizable: true,
			 open: function() {
				$("#preview_div").load("<%= project_study_path(@project, @study) %>");
				window.scrollTo(0, 0);
				},
				title: "Preview Study"
		});
		</script>
		<% end %>

app/views/studies/baselines.html.erb
<div class='tab-div'>
	<h2>Baseline Characteristics</h2><br/><br/>
	<% unless @ef_instruction.blank? %>
		<div class='user_instruction'>
			<strong>Note:</strong> <%= @ef_instruction %>
		</div>
	<%  end %>
	<br/>
<div id="baseline_characteristic_fields_table">
<%= render 'baseline_characteristic_data_points/table' %>
</div>

<br/><br/>
<%= render :partial=>'section_complete_status', :locals=>{:section=>"baselines"} %>
<br/><br/>
<%= render :partial=>'extraction_forms/back_and_continue_buttons_modal' %>

<%= render 'shared/make_editable_and_confirm' %>

<script type="text/javascript">

$("#baseline_characteristic_fields_entry").dialog({
  	autoOpen: false,
	minWidth: 600
});
	

</script>
</div><!-- end tab div -->

app/views/studies/index.html.erb
<h1>Add Studies to This Project</h1>
<br/>
<!-- If this project is able to accept new studies... -->
<% if @project_ready_for_studies[0] %>
	<%# check user privilege %>	
	<% has_privilege = User.current_user_has_study_edit_privilege(@project.id, current_user) %>
	<% if has_privilege %>
		
			<%= link_to (image_tag("Add.png", :style=>"border-style:none;vertical-align:text-top;") + " Add a New Study"), new_project_study_path, :class=>"edit_link" %>

		
		<br/><br/>
		<% unless @studies.empty? %>	
			Below is a list of studies previously added to this project. You may edit or delete these entries using the 
			icons in the right column of the table.
			
			<table class="list_table" id="studies_list_table" summary="studies list table">
			<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Year</th>
			<th>Key Questions Answered</th>
			<th></th>
			</tr>
			
			<% @studies.each do |study| %>
			
				<% study_pub_info = Study.get_primary_pub_info(study.id) %>
				<% if !study_pub_info.nil? %> 
				
						<tr class="<%= cycle("even", "odd") %>">
							<td><%= link_to study_pub_info.title, project_study_path(@project, study) %></td>
							<td><%= study_pub_info.author %></td>
							<td><%= study_pub_info.year %></td>
							<td>
								<% arr = Study.get_key_question_output(study.id) %>
								<%= arr.to_sentence %>
							</td>
							<td>
								<% has_privilege = User.current_user_has_study_edit_privilege(@project.id, current_user) %>
								<% if has_privilege %>

										<%= link_to (image_tag("Pencil.png", :style=>"border-style:none;vertical-align:middle;")), edit_project_study_path(@project, study),:class => 'tooltip_edit_study'%>
										<%= link_to (image_tag("Bin_closed.png", :style=>"border-style:none;vertical-align:middle;")), project_study_path(@project,study), :method=>:delete, :confirm => "Are you sure?", :class=>'tooltip_delete_study' %>
								<% end %>
							</td>
						</tr>
				
				<% end %>
			
			<% end %>
				
		</table>
		
		<% else %>
This project does not yet have any associated studies. Please add a study using the "Add a New Study" button above.
		<% end %>
	<% else %>
		You do not have access to this information. Please contact your project lead to correct this problem.
	<% end %>
	
<!-- if the project is not ready to accept studies, tell them why -->
<% else %>
	<strong>Studies cannot yet be added to this project for the following reasons:</strong>
  <div style="margin-left: 25px;">
		<ul>
	  	<% @project_ready_for_studies[1].each do |reason| %>
	  		<li><%= reason %></li>
	  	<% end %>
	  </ul>
	</div>
  <br/>
  Please correct these problems or contact your project lead before continuing.
<% end %>

	<br/><br/>
  <%= render :partial=>'extraction_forms/back_and_continue_buttons', :locals=>{:previous_url=>"extractionforms",:next_url=>"/projects/#{session[:project_id]}",:previous_title=>"Create Extraction Forms",:next_title=>"Project Summary"} %>	
	

app/views/studies/outcomes.html.erb
<div class='tab-div'>
	<br/>
	<h2>Study Outcomes</h2><br/><br/>
	<% instruction = @extraction_form_outcomes_instr.nil? ? "" : @extraction_form_outcomes_instr.instructions %>
	<% unless instruction.blank? %>
		<div class='user_instruction'>
			<strong>Note:</strong> <%= instruction %>
		</div>
		<br/>
		<br/>
	<%  end %>
	
	<div id="outcomes_table">
	<%= render 'outcomes/table' %>
	</div>

		<br/>
		<div class="actions">
	<button type="submit" class="positive" id="add_outcome_button">
				<%= image_tag "Add.png", :alt => "Add" %>Add a New Outcome
			</button>
			
			<div class="saved" id="saved_item_indicator" style='display:none;'>  Added Successfully <%= image_tag 'Accept.png', :alt => "Accept"  %></div>
	</div>

	<br/><br/>
	<%= render :partial=>'section_complete_status', :locals=>{:section=>"outcomes"} %>
	<br/><br/>
	<%= render :partial=>'extraction_forms/back_and_continue_buttons_modal' %>

	<%= render 'shared/make_editable_and_confirm' %>

</div><!-- end tab div -->

app/views/studies/show.html.erb
<div id='left-navigation-div' tabindex=100>

</div>
<div id='content' tabindex=200>
<h1>Study Preview</h1><br/><br/>
<% begin %>
<!--<div class="centered">
	<%= link_to image_tag("Printer.png") + " Print this page", "#", :onclick => "javascript:window.print()" %> 
	| <%= link_to image_tag("Layout_header.png") + ' Create PDF', study_path(params[:study_id]) + "/index_pdf", :target => "new" %>
	<div class="pdf_plugin_link">
		<%= link_to "download PDF plugin", "https://get.adobe.com/reader/", :target => "new" %> 
		| To save as HTML, click File then Save Page As in your web browser.
	</div>
</div>

<br/>
-->
<!-- SUMMARY HEADING DIV SECTION -->
<div id="display_study_title" style="display:block">
	<div class="summary_heading">Study Title and Description</div>
	<div id="summary_text" style="display:inline;">
		<br/><%= render "completed_tables/study_summary", :study => @study, :study_title => @study_title %>
	</div>
</div>
<br/>

<!-- KEY QUESTIONS DIV SECTION -->
<div id="display_study_keyqs" style="display:block">
	<div class="summary_heading">Key Questions Addressed</div>
	<div id="key_questions_text" style="display:inline;">
		<%= render "completed_tables/key_questions_study", :key_questions => @study_questions, :study => @study, :project => @project %>
	</div>
</div>
<br/>
<!-- PUBLICATION INFORMATION DIV SECTIONS -->
<div id="display_study_pubinfo" style="display:block">
	<div class="summary_heading">Primary Publication Information</div>
	<div id="publications_text">
		<%= render 'completed_tables/primary_publications', :primary_publication => @primary_publication, :study => @study, :project => @project %>	
	</div>
</div>
<br/>
<div id="display_study_secpubinfo" style="display:block">
	<div class="summary_heading">Secondary Publication Information</div>
	<div id="secpublications_text">
		<%= render 'completed_tables/secondary_publications', :study => @study, :project => @project, :secondary_publications => @secondary_publications %>
	</div>
</div>
<br/>
	

<!-- EXTRACTION FORM DATA SECTIONS -->
  
<% for extform in @extraction_forms %>
	<% sections_list = ExtractionFormSection.get_included_sections_by_extraction_form_id(extform.extraction_form_id)%>
	<% @one_extform = ExtractionForm.find(extform.extraction_form_id) %>
		
		<!-- STUDY ARMS DIV SECTION -->		
		<span class='summary_heading'>Extraction Form: <%= @one_extform.title %></span><br/>
		<% if sections_list.include?("arms") %>
			<% @arms = Arm.where(:study_id => @study.id, :extraction_form_id => @one_extform.id).all %>
		
				<div id="display_study_arms_<%= @one_extform.id.to_s %>" style="display:block">
					<div class="summary_heading">Arms</div>
					<div id="study_arms_text">
						<%= render 'completed_tables/study_arms', :arms => @arms, :study => @study, :project => @project %>
					</div>
					</div><br/>
				<% end %>

	
		<!-- STUDY DESIGN DIV SECTION -->
				
		<% if sections_list.include?("design") %>	
			<% @design_detail_extraction_form_fields = DesignDetail.where(:extraction_form_id => @one_extform.id).all %>
	 
				<div id="display_study_design_<%= @one_extform.id.to_s %>" style="display:block">
					<div style="display: none;" class="summary_heading">Design Details</div>
					<div id="study_design_text">
							<%= render 'completed_tables/design_details', :extraction_form => @one_extform, :study => @study, :project => @project, :design_detail_extraction_form_fields => @design_detail_extraction_form_fields %>
					</div>
				</div><br/>
				<% end %>

				
		<!-- BASELINE CHARACTERISTICS DIV SECTION -->
				
		<% if sections_list.include?("baselines") %>	
			<% @baseline_characteristic_extraction_form_fields = BaselineCharacteristic.where(:extraction_form_id => @one_extform.id).all %>	
	  
				<div id="display_study_baselines_<%= @one_extform.id.to_s %>" style="display:block">
					<div class="summary_heading">Baseline Characteristics</div>
					<div id="pop_char_text">
						<%= render 'completed_tables/baseline_characteristics', :extraction_form => @one_extform, :arms=>@arms, :study => @study, :project => @project, :baseline_characteristic_extraction_form_fields => @baseline_characteristic_extraction_form_fields %>
					</div>
				</div><br/>
		<% end %>



		<!-- RESULTS -->
		<br/><br/>
		<div class='summary_heading'>Results &amp; Comparisons</div><br/>
		<% unless @existing_results.empty? %>	
			<%= render :partial=>'outcome_data_entries/existing_results', :locals=>{:no_links=>true} %>
		<% else %>
			No Results found.
		<% end %>
		<br/>

		 <!-- ADVERSE EVENTS SECTION -->
		  
		<% if sections_list.include?("adverse") %>	
			<% @extraction_form_adverse_event_columns = AdverseEventColumn.where(:extraction_form_id => @one_extform.id).all %>
		  
			<div id="display_study_advev_<%= @one_extform.id.to_s %>" style="display:block">
				<div class="summary_heading">Adverse Events</div>
				<div id="adverse_events_text">
					<%= render 'completed_tables/adverse_events', :extraction_form => @one_extform, :adverse_events => @adverse_events, :arms => @arms, :study => @study, :project => @project, :extraction_form_adverse_event_columns => @extraction_form_adverse_event_columns %>	
				</div>
			</div>

		<% end %>
		<br/>
	
		<!-- QUALITY SECTION (DIMENSIONS AND RATING) -->
		
		<% if sections_list.include?("quality") %>	
			<%# @quality_rating = QualityRatingDataPoint.where(:study_id => @study.id).first %>
			<div id="display_study_qualitydimensions_<%= @one_extform.id.to_s %>" style="display:block">
				
				<%= render 'completed_tables/quality_preview', :extraction_form => @one_extform, :study => @study, :project => @project  %>
			</div>
			<br/>
		<% end %>	
	
	
<% end %>

<script type="text/javascript">
	$('.open_comments_link').bind("click", function(event) {

      var self = $(this);
      var qtip = '.qtip.ui-tooltip';
   
      // Create the tooltip
      self.qtip({
         overwrite: false,
		id: $(this).attr('id'),
				 position:{
		 my: 'top right', at: 'bottom center'
		 },
         content: {
			title: {
                  text: 'Item Comments',
                  button: true
			},
			text: "Loading...",
			ajax: {
				url: 'get_comment_content', 
				type: 'POST',
				data: {
					div_id: $(this).attr('id')
				} 
			}			
         },
         show: {
            event: "click", 
            ready: true, 
            solo:  true
         },
         hide: {
            delay: 100,
            event: 'click',
            fixed: true 
         },
         style: {
            classes: 'ui-tooltip-nav ui-tooltip-light', 
            tip: false,
			width: '600'
         },
         events: {
            // Toggle an active class on each menus activator
            toggle: function(event, api) {
               api.elements.target.toggleClass('active', event.type === 'tooltipshow');
            },
			// make qtip movable on render
		   render: function(event, api) {
			   api.elements.tooltip.draggable();
		   }			
         }
      });
   });	
</script>
<% rescue Exception => e %>
	We're sorry, it appears an error has occurred. Please see our contact page and let us know what happened.  
	<%# e.message %><br/>
	<%# e.backtrace %>
<% end %>

<script type='text/javascript'>
$(document).ready(function(){
	$(document).prop("title","Study Preview: <%= @study.id %>");
});
</script>
</div>